name: ahead_app
description: Aplikasi mobile Ahead untuk login, register, dan pilihan bidang IPA atau IPS.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
